services:
  - type: web
    name: google-form-spammer
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python server/app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
